// <auto-generated />
namespace DataEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class trinh_000003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trinh_000003));
        
        string IMigrationMetadata.Id
        {
            get { return "201707280743434_trinh_000003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
